version: '3.4'

services:
  streamlit-app:
    container_name: streamlit-app
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8501:8501"
    stdin_open: true   
    tty: true   
    volumes:
     - ./output:/app/output
     - ./:/app
    environment:
      DOCKER_RUNNING: true